### PR TITLE
Update to work with Crystal 0.35.0

### LINKED ISSUE #5: Broken on 0.28.0
```
$ make
....
in src/resolver.cr:60: undefined method 'key?' for Hash(String, String)

      if value = types.key?(name)
```

### PR DESCRIPTION
**Pull request by dscottboggs**
This resolves #5, as well as a not-yet-reported bug in generating the regex.h file.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Thanks!
